### ISSUE TITLE
gradle ktolin script 有个疑问请教

### ISSUE THREAD

**Issue by Somony** [leobert-lan/DaVinCi#1]
在build.gradle中，如果把一些依赖的远程地址写在另一个gradle文件中，可以通过如下的写法进行依赖的：
```
buildscript { 
  apply from: "gradle/buildscript.gradle", to: buildscript 
}
```

但是迁移到kotlin-dsl后，这种写法失效了

```
buildscript { 
    apply { 
      from("gradle/buildscript.gradle")
      to(buildscript) 
    } 
}
```

作者在迁移时有遇到过这个问题吗？
github上有一个issue，但是我按照给出的方案都没有成功，作者有解决方案吗？

https://github.com/gradle/kotlin-dsl-samples/issues/497

**Comment by leobert-lan** [comment]
**这个问题我并没有遇到过**，因为在DaVinCi中，使用了**buildSrc机制**管理了项目库包依赖的信息。抛开这一点我们**回归到你说的问题**。

本质上这是 `Groovy语法的使用` ，但最重要的，它依旧是在 `定义，配置Gradle的任务`，那么就可以在Gradle源码中找答案。

首先看groovy script的内容，执行 project.buildscript(Closure c) 方法，参数是一个闭包，实际的内容是：

```
//project实现了这一接口
org.gradle.api.plugins.PluginAware#apply(java.util.Map<java.lang.String,?>)
```

我尚未查询 map中约定的“to”的实际作用，但这一语句所创建的map，举个例子：

```
static test(Map<String, ?> var1) {
    println(var1)
}

static void main(String[] args) {
    test from: "a", to: "B"
}
```
打印map的信息： `[from:a, to:B]`

应该不难理解，原先传递的map中含有两个key，以及对应的值分别为：

-  “from”：“gradle/buildscript.gradle”
- “to” : org.gradle.api.Project#getBuildscript 所得到的ScriptHandler对象实例

那么接下来就是看kotlin-dsl中提供了哪些支持，值得一提的是，kts对Closure的支持不如Action好，很可能遇到关联性问题。

---

这几篇文章可能可以从其他角度帮你解决问题：

* https://leobert-lan.github.io/Gradle/post_22.html
* https://leobert-lan.github.io/Groovy/post_23.html

**Comment by leobert-lan** [comment]
我尝试了一下，kts在kotlin-dsl支持下，可以尝试下如下写法：

```
buildscript {
  project.apply(
    from = "xxxx",
    to = project.buildscript
  )
}
```
务必注意，kotlin的lambda和groovy的闭包还是有很大区别的，一定要注意其作用域，这会干扰到你操作的对象。

何况apply本身就是kotlin的内联函数，那不难理解，你列举的做法中，apply中的：
* from和to是两个方法，
* 作用域的this指代的是kotlin-dsl中的ScriptHandlerScope实例，

很显然，ScriptHandlerScope 并没有 `from` 和 `to` 方法，`to` 方法会被认为是Tuples中的内联函数,返回一个 `Pair<ScriptHandlerScope,ScriptHandler>` 实例。

**Comment by leobert-lan** [comment]
当然，具体情况以你的gradle版本为准

**Comment by Somony** [comment]
> 当然，具体情况以你的gradle版本为准

感谢作者的详细解答。我目前用的是gradle7.0版本

**Comment by Somony** [comment]
> 当然，具体情况以你的gradle版本为准

感谢作者的详细解答。目前使用的gradle7.0版本，但是任然没有生效
```
buildscript {
  project.apply(
    from = "xxxx",
    to = project.buildscript
  )
}
```
请问作者使用的gadle版本是多少呢?

**Comment by leobert-lan** [comment]
当时建的模板工程确实是gradle7.0。

我现在用的是手机，没法看源码，建议你追溯下源码，可能这个DSL的api本身也有bug，或者尝试下直接用形参为map的api，直接构建一个map，这样就和groovy脚本的api调用一致了。

**Comment by Somony** [comment]
好的，谢谢

**Comment by leobert-lan** [comment]
今天的提交搞错issue号了。。。
